image: openjdk:11-jdk-slim

stages:
  - build
  - image

build:
  stage: build
  tags:
    - docker
  script: sh ./mvnw package -DskipTests
  after_script:
    - mkdir ./docker
    - mv ./Dockerfile ./docker
    - mv ./target/*.jar ./docker
  artifacts:
    paths:
      - ./docker

build_image:
  dependencies:
    - build
  stage: image
  tags:
    - shell
  before_script:
    - docker info
  script:
    - sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/alexpit
    - sudo docker build -t registry.gitlab.com/alexpitexamples/sberminibank .
    - sudo docker push registry.gitlab.com/alexpitexamples/sberminibank
  after_script:
    - docker logout registry.gitlab.com